"""
Django settings for pattern_service project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = False

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "core",
    "ansible_base.activitystream",
    "ansible_base.rest_filters",
    "ansible_base.jwt_consumer",
    "ansible_base.resource_registry",
    "ansible_base.rbac",
    "pattern_service",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pattern_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pattern_service.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

DISPATCHER_CONFIG = {
    "version": 2,
    "service": {
        "main_kwargs": {"node_id": "pattern-service-a"},
        "process_manager_kwargs": {
            "preload_modules": ["pattern_service.core.tasks.hazmat"]
        },
    },
    "brokers": {
        "pg_notify": {
            "config": {
                "conninfo": (
                    "dbname=pattern_db user=pattern password=pattern123 "
                    "host=postgres port=5432 application_name=dispatcher_pattern_service"
                )
            },
            "sync_connection_factory": "dispatcherd.brokers.pg_notify.connection_saver",
            "channels": ["pattern-service-tasks"],
            "default_publish_channel": "pattern-service-tasks",
        },
        "socket": {"socket_path": "pattern_service_dispatcher.sock"},
    },
    "publish": {"default_control_broker": "socket", "default_broker": "pg_notify"},
}
AUTH_USER_MODEL = "pattern_service.User"

ANSIBLE_BASE_TEAM_MODEL = "pattern_service.Team"
ANSIBLE_BASE_ORGANIZATION_MODEL = "pattern_service.Organization"
ANSIBLE_BASE_RESOURCE_CONFIG_MODULE = "pattern_service.resource_api"

ANSIBLE_BASE_ALLOW_SINGLETON_USER_ROLES = True
ANSIBLE_BASE_ALLOW_SINGLETON_TEAM_ROLES = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "pattern_service.authentication.PatternServiceJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "ansible_base.rbac.api.permissions.AnsibleBaseObjectPermissions",
    ],
}

ANSIBLE_BASE_JWT_KEY = "http://localhost"
