---
ci:
  autoupdate_schedule: monthly
repos:
  - hooks:
      - id: check-github-workflows
      - id: check-metaschema
    repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
