---
ci:
  autoupdate_schedule: monthly
repos:
  - hooks:
      - id: check-github-workflows
      - id: check-metaschema
    repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.2

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--indent=4, --no-sort-keys]
      - id: trailing-whitespace

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        args: [--config, pyproject.toml]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--max-line-length, "90"]

  - repo: https://github.com/ikamensh/flynt/
    rev: 1.0.1
    hooks:
      - id: flynt

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--settings-path, pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        pass_filenames: false
        args: [--config-file=pyproject.toml, --ignore-missing-imports, "."]
        additional_dependencies:
          - types-requests
