# Generated by Django 4.2.22 on 2025-06-23 21:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pattern_created_pattern_created_by_pattern_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='automation_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='controllerlabel',
            name='label_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='patterninstance',
            name='controller_ee_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patterninstance',
            name='controller_project_id',
            field=models.PositiveBigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patterninstance',
            name='organization_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
