# Generated by Django 4.2.22 on 2025-06-23 23:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_automation_automation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='collection_version_uri',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='pattern_definition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patterninstance',
            name='controller_labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='pattern_instances', to='core.controllerlabel'),
        ),
        migrations.AlterField(
            model_name='patterninstance',
            name='controller_project_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
