# Generated by Django 4.2.22 on 2025-06-25 17:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pattern_collection_version_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterninstance',
            name='controller_labels',
            field=models.ManyToManyField(blank=True, related_name='pattern_instances', to='core.controllerlabel'),
        ),
    ]
