# Generated by Django 4.2.23 on 2025-07-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0002_pattern_created_pattern_created_by_pattern_modified_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("details", models.TextField()),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                    ),
                ),
                ("task_id", models.UUIDField(default=None, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
