from django.conf import settings
from django.db import models

from ansible_base.activitystream.models import AuditableModel
from ansible_base.lib.abstract_models import (
    AbstractDABUser,
    AbstractOrganization,
    AbstractTeam,
    CommonModel,
    NamedCommonModel,
)
from ansible_base.lib.utils.models import user_summary_fields
from ansible_base.resource_registry.fields import AnsibleResourceField
from ansible_base.rbac.permission_registry import permission_registry
from django.contrib.auth.hashers import UNUSABLE_PASSWORD_PREFIX, UNUSABLE_PASSWORD_SUFFIX_LENGTH, get_hashers_by_algorithm, identify_hasher, make_password


class Organization(AbstractOrganization):
    class Meta:
        ordering = ['id']
        permissions = [
            (
                'member_organization',
                'User is member of this organization',
            ),
        ]

    resource = AnsibleResourceField(primary_key_field='id')

    users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='member_of_organizations',
        blank=True,
        help_text='The list of users on this organization',
    )

    admins = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='admin_of_organizations',
        blank=True,
        help_text='The list of admins for this organization',
    )

    extra_field = models.CharField(max_length=100, null=True)


def password_is_hashed(password):
    """
    Returns a boolean of whether password is hashed with loaded algorithms
    """
    if password is None:
        return False
    try:
        hasher = identify_hasher(password)
    except ValueError:
        # hasher can't be identified or is not loaded
        return False
    return hasher.algorithm in get_hashers_by_algorithm().keys()


def password_is_usable(password):
    """
    Returns True if password is None or wasn't generated by django.contrib.auth.hashers.make_password(None)
    """
    unusable_password_len = len(UNUSABLE_PASSWORD_PREFIX) + UNUSABLE_PASSWORD_SUFFIX_LENGTH

    return password is None or not (password.startswith(UNUSABLE_PASSWORD_PREFIX) and len(password) == unusable_password_len)


class User(AbstractDABUser, CommonModel, AuditableModel):

    class Meta(AbstractDABUser.Meta):
        ordering = ['id']

    resource = AnsibleResourceField(primary_key_field='id')
    activity_stream_excluded_field_names = ['last_login']

    def save(self, *args, **kwargs):
        if self.password == '':
            self.password = None

        if password_is_usable(self.password) and not password_is_hashed(self.password):
            self.password = make_password(self.password)
        super().save(*args, **kwargs)

    def summary_fields(self):
        return user_summary_fields(self)


class Team(AbstractTeam):
    resource = AnsibleResourceField(primary_key_field='id')
    team_parents = models.ManyToManyField(
        'Team', related_name='team_children', blank=True,
    )

    ignore_relations = []

    class Meta:
        ordering = ['id']
        abstract = False
        unique_together = [('organization', 'name')]
        ordering = ('organization__name', 'name')
        permissions = [('member_team', 'Has all roles assigned to this team')]

    users = models.ManyToManyField(
        User,
        related_name='teams',
        blank=True,
        help_text='The list of users on this team',
    )

    admins = models.ManyToManyField(
        User,
        related_name='teams_administered',
        blank=True,
        help_text='The list of admins for this team',
    )


permission_registry.register(Organization, parent_field_name=None)
permission_registry.register(Team)
