name: Tests

on:
  pull_request:
    branches:
      - main
      - stable-*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: pattern_service.settings
      COMPOSE_COMMAND: docker compose

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Run unit tests
        run: make test

# for SonarCloud code coverage reporting

      - name: Upload Code Coverage Report from Tests
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Save off PR Number
        run: echo "${{ github.event.number }}" > pr-number.txt

      - name: Upload PR Number
        uses: actions/upload-artifact@v4
        with:
          name: pr-number
          path: pr-number.txt
