name: Tests

on:
  pull_request:
    branches:
      - main
      - stable-*
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: pattern_service.settings
      COMPOSE_COMMAND: docker compose

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Run unit tests
        run: make test

# for SonarCloud code coverage reporting
      - name: Upload Code Coverage Report from Tests
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: code.cov

      - name: Save off PR Number
        run: echo "PR ${{ github.event.number }}" > pr_number.txt
      - name: Upload PR Number
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr_number.txt

      - name: SonarCube Static Scans (on push)
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        if: github.event_name == 'push' && startsWith(github.repository, 'ansible-automation-platform') && endsWith(github.repository, '/sonar-cutlery')
        env:
          SONAR_TOKEN: ${{ secrets[format('{0}', vars.SONAR_TOKEN_SECRET_NAME)] }}
        with:
          args: >
            -Dsonar.go.coverage.reportPaths=code.cov
